apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tb-node
  name: tb-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tb-node
  strategy: {}
  template:
    metadata:
      labels:
        app: tb-node
    spec:
      serviceAccountName: default
      volumes:
      - name: vol
        emptyDir: {}
      containers:
      - image: replace
        imagePullPolicy: IfNotPresent
        name: tb-node-container
        volumeMounts:
          - mountPath: /tmp
            name: vol
        securityContext:
          capabilities:
            drop:
             - NET_RAW
          runAsUser: 100
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        resources:
         requests:
          memory: "256Mi"
          cpu: "200m"
         limits:
          memory: "512Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tb-node
  name: tb-node-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tb-node
  type: ClusterIP