apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tb-node
  name: tb-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tb-node
  strategy: {}
  template:
    metadata:
      labels:
        app: tb-node
    spec:
      volumes:
      - name: vol
        emptyDir: {}
      serviceAccountName: default
      containers:
      - image: replace
        name: tb-node-container
        volumeMounts:
        - mountPath: /tmp
          name: vol
        securityContext:
          runAsNonRoot: true
          runAsUser: 100
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tb-node
  name: tb-node-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tb-node
  type: NodePort